import { ServiceState } from '@/types/serviceState';

export const dummy = [
  {
    id: 1,
    name: '홍길동',
    phoneNumber: '010-0000-0000',
    address: '서울시 영등포구',
    serviceState: 'WAITING_FOR_MANAGER_REQUEST',
    createdAt: '2023-03-12',
    memo: '메모끄적끄적길어져라 메모메모',
    code: 'ABC1DR',
  },
  {
    id: 2,
    name: '김아무개',
    phoneNumber: '010-0000-0000',
    address: '서울시 관악구',
    serviceState: 'WAITING_FOR_ACCEPT_MATCHING',
    createdAt: '2023-03-10',
    memo: '메모끄적끄적길어져라 메모메모',
    code: 'ABC1DR',
  },
  {
    id: 3,
    name: '김아무개',
    phoneNumber: '010-0000-0000',
    address: '서울시 관악구',
    serviceState: 'MANAGER_MATCHING_COMPLETED',
    createdAt: '2023-03-10',
    memo: '메모끄적끄적끄적',
    code: 'ABC1DR',
  },
  {
    id: 4,
    name: '김아무개',
    phoneNumber: '010-0000-0000',
    address: '서울시 관악구',
    serviceState: 'SERVICE_COMPLETED',
    createdAt: '2023-03-10',
    memo: '메모끄적끄적',
    code: 'ABC1DR',
  },
  {
    id: 5,
    name: '김아무개',
    phoneNumber: '010-0000-0000',
    address: '서울시 관악구',
    serviceState: 'RESERVATION_CANCELLATION',
    createdAt: '2023-03-10',
    memo: '메모끄적끄적',
    code: 'ABC1DR',
  },
];
